// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.

import one from '../../input/other-test-folder/js/one.js'
import one_1 from '../../input/test/js/one.js'
import two from '../../input/test/js/two.js'
import two_1 from '../../input/other-test-folder/js/two.js'

export default function () {
	one()
	one_1()
	two()
	two_1()
}
