
// Do not edit this file.
// Run "gulp" to generate this file instead.

export type preset =
  | 'es5'
  | 'es5_default_exports'
  | 'es5_named_exports'
  | 'es6'
  | 'es6_default_exports'
  | 'es6_named_exports'
  | 'jade'
  | 'pug'
  | 'sass'
  | 'scss'
  | 'stylus'
  | 'ts'
  | 'ts_default_exports'
  | 'ts_named_exports'
