
// Do not edit this file.
// Do not save this file in source control.
// This file is generated by gulp-file-loader.

import one from "../../other-test-folder/js/one.js";
import one_1 from "./js-input/one.js";
import two from "./js-input/two.js";
import two_1 from "../../other-test-folder/js/two.js";

export default function(){
  one();
  one_1();
  two();
  two_1();
}
