
var template = `
// This file is generated by gulp-file-loader.
// Do not edit this file.
// Do not save this file into source control.

$format[imports]

module.exports = function(){
$format[functions]
}
`;

module.exports = {
  format: {
    imports: 'var $name = require("$path");',
    functions: '  $name();',
  },
  fileName: 'file-loader.js',
  template: template,
}
