
var header = `
// This file is generated by gulp-file-loader.
// Do not edit this file.
// Do not save this file into source control.`;

var template = `
$format[imports]

export default ()=> {
$format[functions]
}
`;

module.exports = {
  format: {
    imports: 'import $name from "$path";',
    functions: '  $name();'
  },
  fileName: 'file-loader.js',
  header: header,
  template: template,
}
