
var template = `
// This file is generated by gulp-file-loader.
// Do not edit this file.
// Do not save this file into source control.

$format[imports]

export default function(){
$format[functions]
}
`;

module.exports = {
  format: {
    imports: 'import $name from "$path";',
    functions: '  $name();'
  },
  fileName: 'file-loader.js',
  template
}
