
var header = `
//- This file is generated by gulp-file-loader.
//- Do not edit this file.
//- Do not save this file into source control.
`;

module.exports = {
  format: 'include $path',
  fileName: 'file-loader.jade',
  header: header,
};
