var header = `
//- This file is generated by gulp-auto-imports.
//- Do not edit this file.
//- Do not save this file into source control.
`

module.exports = {
	format: 'include $path',
	fileName: 'auto-imports.jade',
	header: header,
}
