var header = `
// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.`

module.exports = {
	format: `export { $name } from '$path'`,
	fileName: 'auto-imports.js',
	header: header,
	replace: (currentOutput) => currentOutput.replace(/\.tsx?/g, ''),
}
