
// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.
export { one } from '../../input/test/ts/one'
export { two } from '../../input/test/ts/two'
export { one_1 } from '../../input/other-test-folder/ts/one'
export { two_1 } from '../../input/other-test-folder/ts/two'
