
// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.

import one from '../../input/test/ts/one'
import two from '../../input/test/ts/two'
import one_1 from '../../input/other-test-folder/ts/one'
import two_1 from '../../input/other-test-folder/ts/two'

export default function () {
  one()
  two()
  one_1()
  two_1()
}
