
// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.
export { default as one } from '../../input/test/ts/one'
export { default as two } from '../../input/test/ts/two'
export { default as one_1 } from '../../input/other-test-folder/ts/one'
export { default as two_1 } from '../../input/other-test-folder/ts/two'
