
// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.

import one from './one.js'
import two from './two.js'

export default function () {
  one()
  two()
}
