
// This file is generated by gulp-auto-imports.
// Do not edit this file.
// Do not save this file into source control.

var one = require('../test/js/js-input/one.js')
var two = require('../test/js/js-input/two.js')
var one_1 = require('../other-test-folder/js/one.js')
var two_1 = require('../other-test-folder/js/two.js')

module.exports = function () {
  one()
  two()
  one_1()
  two_1()
}
