
var gulp = require('gulp');
var fileLoader = require('../index');

var header = `
//- Do not edit this file.
//- Do not save this file in source control.
//- This file is generated by gulp-file-loader.
`;

gulp.task('pug:load', function(){

	var dest = 'test/pug';

	return gulp.src([
		'./test/pug/pug-input/**/*.pug',
		'./other-test-folder/pug/**/*.pug'
	])
		.pipe(fileLoader({
			format: 'include $path',
			//needed so that relative paths are able to be generated properly
			dest: dest,
			fileName: 'file-loader.pug',
			header: header,
		}))
		.pipe(gulp.dest(dest))
})

gulp.task('pug', ['pug:load']);

gulp.task('pug:watch', function () {
  gulp.watch([
		'./test/pug/pug-input/**/*.pug',
		'./other-test-folder/pug/**/*.pug'
	], ['pug']);
});
