var gulp = require("gulp");
var fileLoader = require("../index");

var header = `
//- This file is generated by gulp-file-loader.
//- Do not edit this file.
//- Do not save this file into source control.
`;

gulp.task("pug:load", function () {
  var dest = "tests/test/pug";

  return gulp
    .src([
      "./tests/test/pug/pug-input/**/*.pug",
      "./tests/other-test-folder/pug/**/*.pug",
    ])
    .pipe(
      fileLoader({
        format: "include $path",
        //needed so that relative paths are able to be generated properly
        dest: dest,
        fileName: "file-loader.pug",
        header: header,
      })
    )
    .pipe(gulp.dest(dest));
});

gulp.task("pug", ["pug:load"]);

gulp.task("pug:watch", function () {
  gulp.watch(
    [
      "./tests/test/pug/pug-input/**/*.pug",
      "./tests/other-test-folder/pug/**/*.pug",
    ],
    ["pug"]
  );
});
