var gulp = require('gulp')
var autoImports = require('../index')

var header = `
//- This file is generated by gulp-auto-imports.
//- Do not edit this file.
//- Do not save this file into source control.
`

gulp.task('pug:load', function () {
	var dest = 'tests/test/pug'

	return gulp
		.src([
			'./tests/test/pug/pug-input/**/*.pug',
			'./tests/other-test-folder/pug/**/*.pug',
		])
		.pipe(
			autoImports({
				format: 'include $path',
				//needed so that relative paths are able to be generated properly
				dest: dest,
				fileName: 'auto-imports.pug',
				header: header,
			}),
		)
		.pipe(gulp.dest(dest))
})

gulp.task('pug', gulp.series('pug:load'))

gulp.task('pug:watch', function () {
	gulp.watch(
		[
			'./tests/test/pug/pug-input/**/*.pug',
			'./tests/other-test-folder/pug/**/*.pug',
		],
		gulp.series('pug'),
	)
})
