import * as gulp from 'gulp'
import * as sass from 'gulp-sass'
import autoImports from '../index'

var header = `
// This file is generated by gulp-auto-imports.
// Save this file into source control.
// You may rearrange the order of the imports however you like.
// You may NOT make any other alterations to this file.
`

gulp.task('sass:compile', function () {
	return gulp
		.src('./tests/compiler-input/scss/main.scss')
		.pipe(sass().on('error', sass.logError))
		.pipe(gulp.dest('./tests/compiler-output/css/'))
})

gulp.task('sass:load', function () {
	var dest = 'tests/compiler-output/scss'

	'../tests/input/test/scss/'

	return gulp
		.src([
			'./tests/compiler-input/scss/variables/**/*.scss',
			'./tests/compiler-input/scss/mixins/**/*.scss',
			'./tests/compiler-input/scss/components/**/*.scss',
			'./tests/compiler-input/scss/pages/**/*.scss',
			'./tests/input/test/scss/**/*.scss',
		])
		.pipe(
			autoImports({
				format: `@import '$path';`,
				dest: dest,
				fileName: 'auto-imports.scss',
				retainOrder: true,
				header: header,
			}),
		)
		.pipe(gulp.dest(dest))
})

gulp.task('sass', gulp.series('sass:load', 'sass:compile'))

gulp.task('sass:watch', function (done) {
	gulp.watch(
		[
			'./tests/test/scss/**/*.scss',
			'./tests/other-test-folder/scss/**/*.scss',
		],
		gulp.series('sass'),
	)
	done()
})

var sassDest = 'tests/compiler-output/scss/multi-output-result'

function load_sass(folder: string) {
	var dest = sassDest + '/' + folder
	return gulp
		.src('./tests/test/scss/' + folder + '/**/*.scss')
		.pipe(
			autoImports({ preset: 'scss', dest, fileName: 'test-output.scss' }),
		)
		.pipe(gulp.dest(dest))
}

var scssFolders = ['variables', 'mixins', 'components', 'pages']
var scssLoadTasks = scssFolders.map((folderName) => 'load:scss:' + folderName)

scssFolders.forEach((folderName, i) => {
	gulp.task(scssLoadTasks[i], function () {
		return load_sass(folderName)
	})
})

gulp.task('multi-output-test', gulp.parallel(...scssLoadTasks))
