
var gulp = require('gulp');
var sass = require('gulp-sass');

var fileLoader = require('../index');

var header = `
// This file is generated by gulp-file-loader.
// Save this file into source control.
// You may rearrange the order of the imports however you like.
// You may NOT make any other alterations to this file.
`;

gulp.task('sass', ['sass:load'], function(){
	return gulp.src('./tests/test/scss/main.scss')
		.pipe(sass().on('error', sass.logError))
		.pipe(gulp.dest('./tests/test/css'));
});

gulp.task('sass:load', function(){

	var dest = 'tests/test/scss';

	return gulp.src([
		'./tests/test/scss/scss-input/**/*.scss',
		'./tests/other-test-folder/scss/**/*.scss'
	])
		.pipe(fileLoader({
			format: '@import "$path";',
			dest: dest,
			fileName: 'file-loader.scss',
			retainOrder: true,
			header: header,
		}))
		.pipe(gulp.dest(dest))
})

gulp.task('sass:watch', function () {
  gulp.watch([
		'./tests/test/scss/scss-input/**/*.scss',
		'./tests/other-test-folder/scss/**/*.scss'
	], ['sass']);
});
