// Do not edit this file.
// Run "npm run generate" to generate this file instead.
import * as gulp from 'gulp'

import '../input/preset-imports-generator'
import '../input/preset-test-tasks-generator'
import '../input/preset-types-generator'

gulp.task(
   'generate',
   gulp.parallel(
      'preset_imports_generator',
      'preset_test_tasks_generator',
      'preset_types_generator'
   )
)
